#!/usr/bin/env python3
"""Build js/data/icons.js from game-icons.net (CC BY 3.0).

Each icon becomes a list of SVG path strings on a 512x512 canvas.
Pass the path to a checkout of https://github.com/game-icons/icons:

    python3 tools/build_icons.py /path/to/game-icons
"""
import json, os, re, sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "js", "data", "icons.js")

ICONS = {
    # tarot major arcana -- caro-asercion
    **{f"t{i}": f"caro-asercion/tarot-{i:02d}-{n}" for i, n in enumerate([
        "the-fool", "the-magician", "the-high-priestess", "the-empress", "the-emperor", "the-hierophant",
        "the-lovers", "the-chariot", "strength", "the-hermit", "wheel-of-fortune", "justice",
        "the-hanged-man", "death", "temperance", "the-devil", "the-tower", "the-star", "the-moon",
        "the-sun", "judgement", "the-world"])},
    # western constellation figures
    "aries": "darkzaitzev/ram", "taurus": "delapouite/charging-bull", "gemini": "caro-asercion/tarot-06-the-lovers",
    "cancer": "lorc/crab", "leo": "lorc/lion", "virgo": "delapouite/fairy", "libra": "lorc/scales",
    "scorpio": "lorc/scorpion", "sagittarius": "delapouite/centaur", "capricorn": "skoll/goat",
    "aquarius": "caro-asercion/tarot-17-the-star", "pisces": "delapouite/circling-fish",
    # western glyphs
    **{f"g-{n}": f"delapouite/{n}" for n in ["aries", "taurus", "gemini", "cancer", "leo", "virgo", "libra",
                                              "scorpio", "sagittarius", "capricorn", "aquarius", "pisces"]},
    # chinese zodiac animals
    "rat": "lorc/mouse", "ox": "delapouite/bison", "tiger": "delapouite/tiger", "rabbit": "delapouite/rabbit",
    "dragon": "lorc/sea-dragon", "snake": "lorc/snake", "horse": "delapouite/horse-head", "goat": "delapouite/sheep",
    "monkey": "delapouite/gorilla", "rooster": "delapouite/rooster", "dog": "delapouite/sitting-dog", "pig": "skoll/pig",
    # misc
    "tophat": "lorc/top-hat", "mask": "lorc/domino-mask",
}


def main(root):
    out = {}
    for key, rel in ICONS.items():
        with open(os.path.join(root, rel + ".svg"), encoding="utf-8") as f:
            svg = f.read()
        paths = [d for d in re.findall(r'<path[^>]*\sd="([^"]+)"', svg) if d != "M0 0h512v512H0z"]
        out[key] = paths
    js = "/* generated by tools/build_icons.py -- icons by Lorc, Delapouite, Caro Asercion, Skoll and\n" \
         "   DarkZaitzev from game-icons.net, licensed CC BY 3.0 */\n"
    js += "window.MA = window.MA || {};\nMA.ICONS = " + json.dumps(out, separators=(",", ":")) + ";\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"{len(out)} icons, {len(js)} bytes")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "game-icons")
